//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public System.Guid Id { get; set; }
        public System.Guid ReportDataId { get; set; }
        public string DrugCode { get; set; }
        public string DrugDescription { get; set; }
        public string Dosage { get; set; }
        public string Route { get; set; }
        public string Frequency { get; set; }
        public string Duration { get; set; }
        public string Cautionary { get; set; }
        public string Instruction { get; set; }
        public string SpecialInstruction { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string DoctorName { get; set; }
    
        public virtual ReportData ReportData { get; set; }
    }
}
