//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRS.Module.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelDifferenceAspect
    {
        private int _iD;
    	public int ID 
    	{ 
    		get { return _iD; } 
    		protected set
    		{
    			if (value != _iD) {
    				_iD = value;
    				 OnIDChanged();
    			}
    		} 
    	}
    	partial void OnIDChanged(); 
    
        private string _name;
    	public string Name 
    	{ 
    		get { return _name; } 
    		set
    		{
    			if (value != _name) {
    				_name = value;
    				 OnNameChanged();
    			}
    		} 
    	}
    	partial void OnNameChanged(); 
    
        private string _xml;
    	public string Xml 
    	{ 
    		get { return _xml; } 
    		set
    		{
    			if (value != _xml) {
    				_xml = value;
    				 OnXmlChanged();
    			}
    		} 
    	}
    	partial void OnXmlChanged(); 
    
    
        public virtual ModelDifference Owner { get; set; }
    }
}
