//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRS.Module.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelDifference
    {
        public ModelDifference()
        {
            this.Aspects = new List<ModelDifferenceAspect>();
        }
    
        private int _iD;
    	public int ID 
    	{ 
    		get { return _iD; } 
    		protected set
    		{
    			if (value != _iD) {
    				_iD = value;
    				 OnIDChanged();
    			}
    		} 
    	}
    	partial void OnIDChanged(); 
    
        private string _userId;
    	public string UserId 
    	{ 
    		get { return _userId; } 
    		set
    		{
    			if (value != _userId) {
    				_userId = value;
    				 OnUserIdChanged();
    			}
    		} 
    	}
    	partial void OnUserIdChanged(); 
    
        private string _contextId;
    	public string ContextId 
    	{ 
    		get { return _contextId; } 
    		set
    		{
    			if (value != _contextId) {
    				_contextId = value;
    				 OnContextIdChanged();
    			}
    		} 
    	}
    	partial void OnContextIdChanged(); 
    
        private int _version;
    	public int Version 
    	{ 
    		get { return _version; } 
    		set
    		{
    			if (value != _version) {
    				_version = value;
    				 OnVersionChanged();
    			}
    		} 
    	}
    	partial void OnVersionChanged(); 
    
    
        public virtual ICollection<ModelDifferenceAspect> Aspects { get; set; }
    }
}
