//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRS.Module.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Users = new List<User>();
            this.TypePermissions = new List<TypePermissionObject>();
            this.ChildRoles = new List<Role>();
            this.ParentRoles = new List<Role>();
        }
    
        private int _iD;
    	public int ID 
    	{ 
    		get { return _iD; } 
    		protected set
    		{
    			if (value != _iD) {
    				_iD = value;
    				 OnIDChanged();
    			}
    		} 
    	}
    	partial void OnIDChanged(); 
    
        private string _name;
    	public string Name 
    	{ 
    		get { return _name; } 
    		set
    		{
    			if (value != _name) {
    				_name = value;
    				 OnNameChanged();
    			}
    		} 
    	}
    	partial void OnNameChanged(); 
    
        private bool _isAdministrative;
    	public bool IsAdministrative 
    	{ 
    		get { return _isAdministrative; } 
    		set
    		{
    			if (value != _isAdministrative) {
    				_isAdministrative = value;
    				 OnIsAdministrativeChanged();
    			}
    		} 
    	}
    	partial void OnIsAdministrativeChanged(); 
    
        private bool _canEditModel;
    	public bool CanEditModel 
    	{ 
    		get { return _canEditModel; } 
    		set
    		{
    			if (value != _canEditModel) {
    				_canEditModel = value;
    				 OnCanEditModelChanged();
    			}
    		} 
    	}
    	partial void OnCanEditModelChanged(); 
    
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<TypePermissionObject> TypePermissions { get; set; }
        public virtual ICollection<Role> ChildRoles { get; set; }
        public virtual ICollection<Role> ParentRoles { get; set; }
    }
}
