//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRS.Module.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecuritySystemMemberPermissionsObject
    {
        private int _iD;
    	public int ID 
    	{ 
    		get { return _iD; } 
    		set
    		{
    			if (value != _iD) {
    				_iD = value;
    				 OnIDChanged();
    			}
    		} 
    	}
    	partial void OnIDChanged(); 
    
        private string _members;
    	public string Members 
    	{ 
    		get { return _members; } 
    		set
    		{
    			if (value != _members) {
    				_members = value;
    				 OnMembersChanged();
    			}
    		} 
    	}
    	partial void OnMembersChanged(); 
    
        private bool _allowRead;
    	public bool AllowRead 
    	{ 
    		get { return _allowRead; } 
    		set
    		{
    			if (value != _allowRead) {
    				_allowRead = value;
    				 OnAllowReadChanged();
    			}
    		} 
    	}
    	partial void OnAllowReadChanged(); 
    
        private bool _allowWrite;
    	public bool AllowWrite 
    	{ 
    		get { return _allowWrite; } 
    		set
    		{
    			if (value != _allowWrite) {
    				_allowWrite = value;
    				 OnAllowWriteChanged();
    			}
    		} 
    	}
    	partial void OnAllowWriteChanged(); 
    
        private string _criteria;
    	public string Criteria 
    	{ 
    		get { return _criteria; } 
    		set
    		{
    			if (value != _criteria) {
    				_criteria = value;
    				 OnCriteriaChanged();
    			}
    		} 
    	}
    	partial void OnCriteriaChanged(); 
    
    
        public virtual TypePermissionObject Owner { get; set; }
    }
}
