//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRS.Module.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypePermissionObject
    {
        public TypePermissionObject()
        {
            this.MemberPermissions = new List<SecuritySystemMemberPermissionsObject>();
            this.ObjectPermissions = new List<SecuritySystemObjectPermissionsObject>();
        }
    
        private int _iD;
    	public int ID 
    	{ 
    		get { return _iD; } 
    		protected set
    		{
    			if (value != _iD) {
    				_iD = value;
    				 OnIDChanged();
    			}
    		} 
    	}
    	partial void OnIDChanged(); 
    
        private bool _allowRead;
    	public bool AllowRead 
    	{ 
    		get { return _allowRead; } 
    		set
    		{
    			if (value != _allowRead) {
    				_allowRead = value;
    				 OnAllowReadChanged();
    			}
    		} 
    	}
    	partial void OnAllowReadChanged(); 
    
        private bool _allowWrite;
    	public bool AllowWrite 
    	{ 
    		get { return _allowWrite; } 
    		set
    		{
    			if (value != _allowWrite) {
    				_allowWrite = value;
    				 OnAllowWriteChanged();
    			}
    		} 
    	}
    	partial void OnAllowWriteChanged(); 
    
        private bool _allowCreate;
    	public bool AllowCreate 
    	{ 
    		get { return _allowCreate; } 
    		set
    		{
    			if (value != _allowCreate) {
    				_allowCreate = value;
    				 OnAllowCreateChanged();
    			}
    		} 
    	}
    	partial void OnAllowCreateChanged(); 
    
        private bool _allowDelete;
    	public bool AllowDelete 
    	{ 
    		get { return _allowDelete; } 
    		set
    		{
    			if (value != _allowDelete) {
    				_allowDelete = value;
    				 OnAllowDeleteChanged();
    			}
    		} 
    	}
    	partial void OnAllowDeleteChanged(); 
    
        private bool _allowNavigate;
    	public bool AllowNavigate 
    	{ 
    		get { return _allowNavigate; } 
    		set
    		{
    			if (value != _allowNavigate) {
    				_allowNavigate = value;
    				 OnAllowNavigateChanged();
    			}
    		} 
    	}
    	partial void OnAllowNavigateChanged(); 
    
        private string _targetTypeFullName;
    	protected string TargetTypeFullName 
    	{ 
    		get { return _targetTypeFullName; } 
    		set
    		{
    			if (value != _targetTypeFullName) {
    				_targetTypeFullName = value;
    				 OnTargetTypeFullNameChanged();
    			}
    		} 
    	}
    	partial void OnTargetTypeFullNameChanged(); 
    
    
        public virtual Role Role { get; set; }
        public virtual ICollection<SecuritySystemMemberPermissionsObject> MemberPermissions { get; set; }
        public virtual ICollection<SecuritySystemObjectPermissionsObject> ObjectPermissions { get; set; }
    }
}
