//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRS.Module.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.IsActive = true;
            this.Roles = new List<Role>();
        }
    
        private int _iD;
    	public int ID 
    	{ 
    		get { return _iD; } 
    		protected set
    		{
    			if (value != _iD) {
    				_iD = value;
    				 OnIDChanged();
    			}
    		} 
    	}
    	partial void OnIDChanged(); 
    
        private string _userName;
    	public string UserName 
    	{ 
    		get { return _userName; } 
    		set
    		{
    			if (value != _userName) {
    				_userName = value;
    				 OnUserNameChanged();
    			}
    		} 
    	}
    	partial void OnUserNameChanged(); 
    
        private bool _isActive;
    	public bool IsActive 
    	{ 
    		get { return _isActive; } 
    		set
    		{
    			if (value != _isActive) {
    				_isActive = value;
    				 OnIsActiveChanged();
    			}
    		} 
    	}
    	partial void OnIsActiveChanged(); 
    
        private bool _changePasswordOnFirstLogon;
    	public bool ChangePasswordOnFirstLogon 
    	{ 
    		get { return _changePasswordOnFirstLogon; } 
    		set
    		{
    			if (value != _changePasswordOnFirstLogon) {
    				_changePasswordOnFirstLogon = value;
    				 OnChangePasswordOnFirstLogonChanged();
    			}
    		} 
    	}
    	partial void OnChangePasswordOnFirstLogonChanged(); 
    
        private string _storedPassword;
    	protected string StoredPassword 
    	{ 
    		get { return _storedPassword; } 
    		set
    		{
    			if (value != _storedPassword) {
    				_storedPassword = value;
    				 OnStoredPasswordChanged();
    			}
    		} 
    	}
    	partial void OnStoredPasswordChanged(); 
    
    
        public virtual ICollection<Role> Roles { get; set; }
    }
}
