//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportData()
        {
            this.Prescriptions = new HashSet<Prescription>();
        }
    
        public System.Guid Id { get; set; }
        public string Type { get; set; }
        public System.Guid PatientId { get; set; }
        public string MRN { get; set; }
        public string VisitNumber { get; set; }
        public Nullable<long> ID_Old { get; set; }
        public Nullable<int> TestID { get; set; }
        public string TestName { get; set; }
        public string Report { get; set; }
        public string ImpressionConclusion { get; set; }
        public string ProcedureDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string NormalResult { get; set; }
        public string Result { get; set; }
        public string Description { get; set; }
    
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
    }
}
